export const BLOG_SUCCESS = "BLOG_SUCCESS";
export const BLOG_FAILURE = "BLOG_FAILURE";
export const BLOG_CATEGORY_SUCCESS = "BLOG_CATEGORY_SUCCESS";
export const BLOG_CATEGORY_FAILURE = "BLOG_CATEGORY_FAILURE";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAILURE = "CATEGORY_FAILURE";
export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_FAILURE = "COMMENT_FAILURE";
export const BLOG_ID_SUCCESS = "BLOG_ID_SUCCESS"
export const BLOG_ID_FAILURE = "BLOG_ID_FAILURE"
export const USER_SUCCESS = "USER_SUCCESS"
export const USER_FAILURE = "USER_FAILURE"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE"
export const USER_POST_SUCCESS = "USER_POST_SUCCESS"
export const USER_POST_FAILURE = "USER_POST_FAILURE"
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS"
export const EDIT_POST_FAILURE = "EDIT_POST_FAILURE"
export const GETTING_DATA = "GETTING_DATA"







